// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmL2T6LYjadLnvYlJ2p9mXU_TVgBwMQ5M',
    appId: '1:542354591142:web:0ddb2a78bbb005bb78d367',
    messagingSenderId: '542354591142',
    projectId: 'noman-mynotes-flutter-projects',
    authDomain: 'noman-mynotes-flutter-projects.firebaseapp.com',
    storageBucket: 'noman-mynotes-flutter-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMnwRSGrAdL4MhrUdfwEpifHsO8JOmNBM',
    appId: '1:542354591142:android:ee85ab660337cb0778d367',
    messagingSenderId: '542354591142',
    projectId: 'noman-mynotes-flutter-projects',
    storageBucket: 'noman-mynotes-flutter-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJSqzuVUEdd81sxjtVamcSQ6KK6X7dVI',
    appId: '1:542354591142:ios:2afc41f90512cb8978d367',
    messagingSenderId: '542354591142',
    projectId: 'noman-mynotes-flutter-projects',
    storageBucket: 'noman-mynotes-flutter-projects.appspot.com',
    iosClientId: '542354591142-t3ikvoo087kkmdeohfpct8mdtguggg50.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJSqzuVUEdd81sxjtVamcSQ6KK6X7dVI',
    appId: '1:542354591142:ios:2afc41f90512cb8978d367',
    messagingSenderId: '542354591142',
    projectId: 'noman-mynotes-flutter-projects',
    storageBucket: 'noman-mynotes-flutter-projects.appspot.com',
    iosClientId: '542354591142-t3ikvoo087kkmdeohfpct8mdtguggg50.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
